// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeCu1bPYwG91ZJ1dktchquG3DFPw7YW7k',
    appId: '1:974117334441:web:6ff977105dc3b4feafa8b8',
    messagingSenderId: '974117334441',
    projectId: 'campusplus-e584d',
    authDomain: 'campusplus-e584d.firebaseapp.com',
    storageBucket: 'campusplus-e584d.firebasestorage.app',
    measurementId: 'G-H55HEXWB2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmHT0vTxW_eVVTqcvielhctPTHTml--4Q',
    appId: '1:974117334441:android:c2c62c8c5517a544afa8b8',
    messagingSenderId: '974117334441',
    projectId: 'campusplus-e584d',
    storageBucket: 'campusplus-e584d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbDkASa1SjIrFK7_R61jrzMdUI08RkOkk',
    appId: '1:974117334441:ios:4c67b1357213f63eafa8b8',
    messagingSenderId: '974117334441',
    projectId: 'campusplus-e584d',
    storageBucket: 'campusplus-e584d.firebasestorage.app',
    iosBundleId: 'com.example.campusPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbDkASa1SjIrFK7_R61jrzMdUI08RkOkk',
    appId: '1:974117334441:ios:4c67b1357213f63eafa8b8',
    messagingSenderId: '974117334441',
    projectId: 'campusplus-e584d',
    storageBucket: 'campusplus-e584d.firebasestorage.app',
    iosBundleId: 'com.example.campusPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeCu1bPYwG91ZJ1dktchquG3DFPw7YW7k',
    appId: '1:974117334441:web:58e6b34729afda6aafa8b8',
    messagingSenderId: '974117334441',
    projectId: 'campusplus-e584d',
    authDomain: 'campusplus-e584d.firebaseapp.com',
    storageBucket: 'campusplus-e584d.firebasestorage.app',
    measurementId: 'G-HCTLBLCX3Q',
  );
}
